In [1]:
import numpy as np

# Vectors

In [3]:
v1 = np.array([1, 2, 3])
v2 = np.array([3, 2, 1])

print("Sum:", v1 + v2)
print("Inner product:", np.dot(v1, v2))
print("Subtraction:", v1 - v2)
print("Outer product:", np.outer(v1, v2))
print("Inner product (using @):", v1 @ v2)

Sum: [4 4 4]
Inner product: 10
Subtraction: [-2  0  2]
Outer product: [[3 2 1]
 [6 4 2]
 [9 6 3]]
Inner product (using @): 10


# Matrices

In [11]:
a1 = np.array([
    [1, 2],
    [4, 5]
])
a2 = np.array([
    [7, 8],
    [10, 11]
])

print("Sum:\n", a1 + a2)
print("Subtraction:\n", a1 - a2)
print("Matrix product (using @):\n", a1 @ a2)
print("Transpose:\n", np.transpose(a1))
print("Determinant:\n", np.linalg.det(a1))

Sum:
 [[ 8 10]
 [14 16]]
Subtraction:
 [[-6 -6]
 [-6 -6]]
Matrix product (using @):
 [[27 30]
 [78 87]]
Transpose:
 [[1 4]
 [2 5]]
Determinant:
 -2.9999999999999996
